python1812/python_3/day08_爱鲜蜂项目流程/DjangoDay08/DjangoDay08/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls', namespace='app')),
]

python1812/python_3/day08_爱鲜蜂项目流程/DjangoDay08/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^newsdetail/(\d+)/$', views.newsdetail, name='newsdetail'),
    url(r'^bookdetail/(\d+)/$', views.bookdetail, name='bookdetail'),
]

python1812/python_3/day08_爱鲜蜂项目流程/DjangoDay08/app/models.py
from django.db import models
from tinymce.models import HTMLField


class News(models.Model):
    n_title = models.CharField(max_length=100)
    n_time = models.DateTimeField(auto_now=True)

    # 富文本定制
    # n_content = models.TextField()
    n_content = HTMLField()

    def __str__(self):
        return self.n_title


class Book(models.Model):
    b_title = models.CharField(max_length=100)
    b_time = models.DateTimeField(auto_now=True)
    b_content = models.TextField()

    def __str__(self):
        return self.b_title

python1812/python_3/day08_爱鲜蜂项目流程/DjangoDay08/app/views.py
from django.shortcuts import render

# Create your views here.
from app.models import News, Book


def index(request):

    news_list = News.objects.all()

    books = Book.objects.all()

    return render(request, 'index.html', context={'news_list':news_list, 'books':books})


def newsdetail(request, news_id):
    news = News.objects.get(pk=news_id)

    return render(request, 'newsdetail.html', context={'news':news})


def bookdetail(request, book_id):
    book = Book.objects.get(pk=book_id)

    return render(request, 'bookdetail.html', context={'book':book})

python1812/python_3/day08_爱鲜蜂项目流程/DjangoDay08/templates/bookdetail.html
{% load markdown_deux_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ book.b_title }}</title>
</head>
<body>

<h2>{{ book.b_title }}</h2>
<p>
    {{ book.b_time }}
</p>
<div class="content">
    {{ book.b_content | markdown }}
</div>

</body>
</html>

python1812/python_3/day08_爱鲜蜂项目流程/DjangoDay08/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
        .view {
            height: 50px;
        }

        .view1 {
            width: 100px;
            background: red;
            float: left;
        }

        .view2 {
            width: 50px;
            background: blue;
            float: left;
            margin-left: 30px;
        }

        .view3 {
            width: 120px;
            background: purple;
            float: right;
        }

        .dropdown{
            float: right;
            font-size: 30px;
        }
        .dropdown button{
            background: red;
        }
        .dropdown  span{
            color: white;
            font-size: 30px;
        }
    </style>
</head>
<body>

<div class="container">
    <nav class="navbar navbar-default">
        <div class="view view1"></div>

        <div class="view view2 hidden-sm hidden-xs"></div>

        <div class="view view3 hidden-sm hidden-xs"></div>


        <div class="dropdown visible-sm-block visible-xs-block">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="true">
                <span class="glyphicon glyphicon-home"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
            </ul>
        </div>
    </nav>

    <ul>
        {% for news in news_list %}
            <li>
                <a href="{% url 'app:newsdetail' news.id %}">{{ news.n_title }}</a>
            </li>
        {% endfor %}
    </ul>

    <br>
    <br>
    <hr>
    <ul>
        {% for book in books %}
        <li>
            <a href="{% url 'app:bookdetail' book.id %}">{{ book.b_title }}</a>
        </li>
        {% endfor %}

    </ul>
</div>

</body>
</html>

python1812/python_3/day08_爱鲜蜂项目流程/DjangoDay08/templates/newsdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ news.n_title }}</title>
</head>
<body>

<h2>{{ news.n_title }}</h2>
<p>
    {{ news.n_time }}
</p>
<div class="content">
    {{ news.n_content | safe }}
</div>

</body>
</html>